name: Build & Publish tundra-cli

permissions:
  contents: write

on:
  release:
    types: [created, published, prereleased]
  workflow_dispatch: {}          

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build tundra-cli
      run: cargo build --release -p tundra-cli

    # ---------- Linux packaging ----------
    - name: Package (Linux)
      if: runner.os == 'Linux'
      id: package_linux
      run: |
        cd target/release
        tar czvf tundra-cli-${{ github.event.release.tag_name }}-linux-x86_64.tar.gz tundra-cli
        echo "path=$(pwd)/tundra-cli-${{ github.event.release.tag_name }}-linux-x86_64.tar.gz" >> $GITHUB_OUTPUT

    - name: Upload asset (Linux)
      if: runner.os == 'Linux'
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ steps.package_linux.outputs.path }}

    # ---------- Windows packaging ----------
    - name: Package (Windows)
      if: runner.os == 'Windows'
      id: package_windows
      shell: pwsh
      run: |
        $zipPath = "target/release/tundra-cli-${{ github.event.release.tag_name }}-windows-x86_64.zip"
        Compress-Archive `
          -Path  "target/release/tundra-cli.exe" `
          -DestinationPath $zipPath -Force
        "path=$zipPath" >> $env:GITHUB_OUTPUT

    - name: Upload asset (Windows)
      if: runner.os == 'Windows'
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ steps.package_windows.outputs.path }}
